const Muhammadiya = {
    id: "muhammadiya",
    titleAr: "محمدية",
    titleEn: "Muhammadiya",
    shortTitle: "Muhammadiya",
    info: "En vacker hyllning till Profeten Muhammad (fred vare över honom), som beskriver hans upphöjda karaktär och egenskaper.",
    verses: [
      { type: "verse", number: "1", ar: "مُحَمَّدٌ أَشْرَفُ الْأَعْرَابِ وَالْعَجَمِ<br>مُحَمَّدٌ خَيْرُ مَنْ يَمْشِي عَلَى قَدَمِ", tl: "Muhammadun ashrafu l-a'rabi wa l-'ajami<br>Muhammadun khayru man yamshi 'ala qadami", en: "Muhammad - noblest of the Arabs and the non-Arabs<br>Muhammad - best of all those who walk upon two feet" },
      { type: "verse", number: "2", ar: "مُحَمَّدٌ بَاسِطُ الْمَعْرُوفِ جَامِعُهُ<br>مُحَمَّدٌ صَاحِبُ الْإِحْسَانِ وَالْكَرَمِ", tl: "Muhammadun basitu l-ma'rufi jami'uhu<br>Muhammadun sahibu l-ihsani wa l-karami", en: "Muhammad - most expansive giver of all good things<br>Muhammad - the master of excellence and generosity" },
      { type: "verse", number: "3", ar: "مُحَمَّدٌ تَاجُ رُسْلِ اللهِ قَاطِبَةً<br>مُحَمَّدٌ صَادِقُ الْأَقْوَالِ وَالْكَلِمِ", tl: "Muhammadun taju rusli Llahi qatibatan<br>Muhammadun sadiqu l-aqwali wa l-kalimi", en: "Muhammad - crown of the Messengers of God without exception<br>Muhammad - in speech and word the one most true" },
      { type: "verse", number: "4", ar: "مُحَمَّدٌ ثَابِتُ الْمِيثَاقِ حَافِظُهُ<br>مُحَمَّدٌ طَيِّبُ الْأَخْلَاقِ وَالشِّيَمِ", tl: "Muhammadun thabitu l-mithaqi hafizuhu<br>Muhammadun tayyibu l-akhlaqi wa sh-shiyami", en: "Muhammad - utterly reliable in keeping trusts<br>Muhammad - whose character and qualities are excellent indeed" },
      { type: "verse", number: "5", ar: "مُحَمَّدٌ رُوِيَتْ بِالنُّورِ طِينَتُهُ<br>مُحَمَّدٌ لَمْ يَزَلْ نُورًا مِنَ الْقِدَمِ", tl: "Muhammadun ruwiyat bi n-nuri tinatehu<br>Muhammadun lam yazal nuran mina l-qidami", en: "Muhammad - his substance watered by light<br>Muhammad - a light still shining from before eternity" },
      { type: "verse", number: "6", ar: "مُحَمَّدٌ حَاكِمٌ بِالْعَدْلِ ذُو شَرَفٍ<br>مُحَمَّدٌ مَعْدِنُ الْإِنْعَامِ وَالْحِكَمِ", tl: "Muhammadun hakimun bi l-'adli dhu sharafin<br>Muhammadun ma'dinu l-in'ami wa l-hikami", en: "Muhammad - fair and wise in judgement, the noble one<br>Muhammad - source of kindness and wisdom" },
      { type: "verse", number: "7", ar: "مُحَمَّدٌ خَيْرُ خَلْقِ اللهِ مِنْ مُضَرٍ<br>مُحَمَّدٌ خَيْرُ رُسْلِ اللهِ كُلِّهِمِ", tl: "Muhammadun khayru khalqi Llahi min Mudarin<br>Muhammadun khayru rusli Llahi kullihimi", en: "Muhammad - finest of God’s creation, who came from Mudar<br>Muhammad - of all God’s Messengers the best" },
      { type: "verse", number: "8", ar: "مُحَمَّدٌ دِينُهُ حَقٌّ نَدِينُ بِهِ<br>مُحَمَّدٌ مُجْمِلًا حَقًا عَلَى عَلَمِ", tl: "Muhammadun dinuhu haqqun nadinu bihi<br>Muhammadun mujmilan haqqan 'ala 'alami", en: "Muhammad - his creed is true, by it we profess our faith<br>Muhammad - eminent, the embodiment of truth" },
      { type: "verse", number: "9", ar: "مُحَمَّدٌ ذِكْرُهُ رَوْحٌ لِأَنْفُسِنَا<br>مُحَمَّدٌ شُكْرُهُ فَرْضٌ عَلَى الْأُمَمِ", tl: "Muhammadun dhikruhu rawhun li anfusina<br>Muhammadun shukruhu fardun 'ala l-umami", en: "Muhammad - to mention him brings refreshment to our souls<br>Muhammad - praising him is a duty upon all peoples" },
      { type: "verse", number: "10", ar: "مُحَمَّدٌ زِينَةُ الدُّنْيَا وَبَهْجَتُهَا<br>مُحَمَّدٌ كَاشِفُ الْغُمَّاتِ وَالْظُلَمِ", tl: "Muhammadun zinatu d-dunya wa bahjatuha<br>Muhammadun kashifu l-ghummati wa z-zulami", en: "Muhammad - the beauty of the world and its splendour<br>Muhammad - who lifts the veils of darkness and distress" },
      { type: "verse", number: "11", ar: "مُحَمَّدٌ سَيِّدٌ طَابَتْ مَنَاقِبُهُ<br>مُحَمَّدٌ صَاغَهُ الرَّحْمٰنُ بِالنِّعَمِ", tl: "Muhammadun sayyidun tabat manaqibuhu<br>Muhammadun saghahu r-rahmanu bi-n-ni'ami", en: "Muhammad - a master, whose virtues bring delight<br>Muhammad - the Most Merciful fashioned him from grace" },
      { type: "verse", number: "12", ar: "مُحَمَّدٌ صَفْوَةُ الْبَارِي وَخِيرَتُهُ<br>مُحَمَّدٌ طَاهِرٌ مِنْ سَائِرِ التُّهَمِ", tl: "Muhammadun safwatu l-bari wa khiratuhu<br>Muhammadun tahirun min sai'ri t-tuhami", en: "Muhammad - the flower of the Creator and His elect<br>Muhammad - pure beyond all suspicion" },
      { type: "verse", number: "13", ar: "مُحَمَّدٌ ضَاحِكٌ لِلضَّيْفِ مُكْرِمُهُ<br>مُحَمَّدٌ جَارُهُ وَاللهِ لَمْ يُضَمِ", tl: "Muhammadun dahikun li-d-dayfi mukrimuhu<br>Muhammadun jaruhu wa Llahi lam yudami", en: "Muhammad - smiling and cheerful with his guest to honour him<br>Muhammad - by God, no neighbour of his was ever wronged!" },
      { type: "verse", number: "14", ar: "مُحَمَّدٌ طَابَتِ الدُّنْيَا بِبِعْثَتِهِ<br>مُحَمَّدٌ جَاءَ بِالْآيَاتِ وَالْحِكَمِ", tl: "Muhammadun tabati-d-dunya bi bi'thatihi<br>Muhammadun ja'a bi l-ayati wa l-hikami", en: "Muhammad - this world was made delightful by his being sent<br>Muhammad - he came with signs and with wisdom" },
      { type: "verse", number: "15", ar: "مُحَمَّدٌ يَوْمَ بَعْثِ النَّاسِ شَافِعُنَا<br>مُحَمَّدٌ نُورُهُ الْهَادِي مِنَ الظُّلَمِ", tl: "Muhammadun yawma ba'thi n-nasi shafi'una<br>Muhammadun nuruhu l-hadi mina-z-zulami", en: "Muhammad - our intercessor on the Day mankind is resurrected<br>Muhammad - whose light is the guide out of darkness" },
      { type: "verse", number: "16", ar: "مُحَمَّدٌ قَائِمٌ لِلّٰهِ ذُو هِمَمٍ<br>مُحَمَّدٌ خَاتَمٌ لِلرُّسْلِ كُلِّهِمِ", tl: "Muhammadun qa'imun li-Llahi dhu himamin<br>Muhammadun khatamun li-r-rusli kullihimi", en: "Muhammad - dedicated to God, he of the highest aspiration<br>Muhammad - the Seal of the Messengers, every one of them." }
    ]
  };
  
  export default Muhammadiya;